version: '3'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - "443:5000/tcp"
    container_name: registry
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - ./foreign/docker-registry-certs/certs/data:/var/lib/registry
      - ./foreign/docker-registry-certs/certs:/certs
      - ./foreign/docker-registry-certs/certs/auth:/auth
